# Generated by Django 4.2.7 on 2023-12-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_details_id_details_employee_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='employee_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
