# Generated by Django 4.2.7 on 2023-12-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_details_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='employee_code',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
