# Generated by Django 4.2.7 on 2023-12-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_details_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='employee_code',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
