# Generated by Django 4.2.7 on 2023-12-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_details_employee_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='employee_code',
            new_name='e_id',
        ),
    ]
