# Generated by Django 4.2.7 on 2023-12-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_employee_code_details_e_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='employee_code',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
