# Generated by Django 4.2.7 on 2023-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_details_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
