# Generated by Django 4.2.7 on 2023-12-02 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_details_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 2, 23, 5, 42, 33504, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
