# Generated by Django 4.2.7 on 2023-12-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_details_created_at_details_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced')], max_length=10, null=True),
        ),
    ]
