# Generated by Django 4.2.7 on 2023-12-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='current_package',
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='monthly_income',
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
    ]
