# Generated by Django 5.0 on 2023-12-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='current_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='monthly_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
